/* This guess the number game is a short TypeScript/Node.js project that allows the users to guess the number
generated by the computer. There are also several ways to alter the game, like adding more rounds or displaying
the score. It's quite simple and users the random function to generate a number. */
import inquirer from 'inquirer';
do {
    let number = Math.floor(Math.random() * 10);
    let answer = await inquirer.prompt([
        {
            type: "number",
            name: "user",
            message: "Write Your Number Between 1 To 10 "
        }
    ]);
    let { user } = answer;
    if (user === number) {
        console.log("Yalla Habibi....! You Won Choosing Correct Number");
        process.exit();
    }
    else {
        console.log("Khallas Maafi... You Loss Choosing Wrong Number");
        console.log("Correct Answer Is", number);
    }
} while (true);
//Program End
